### DISCUSSION TITLE
Convert map into list of maps

### DISCUSSION THREAD

**Discussion by Stolz** [antonmedv/expr#782] [Q&A]
I want to convert this object

```yaml
{
  first: {
    id: 1,
    status: Succeeded,
  },
  second: {
    id: 2,
    status: Skipped,
  }
}
```

Into this list of objects
```yaml
[
  {
    name: first,  
    id: 1,
    status: Succeeded,
  },
  {
    name: second,  
    id: 2,
    status: Skipped,
  }
]
```

The closest I can get is using
```golang
let payload = {
  first: {
    id: '1',
    status: 'Succeeded'
  },
  second: {
    id: '2',
    status: 'Skipped'
  }
};

map(keys(payload), {
    {name:#,data:payload[#]}
})
```
which yields
```yaml
[
  {
    name: first,
    data: {
      id: 1,
      status: Succeeded
    }
  },
  {
    name: second,
    data: {
      id: 2,
      status: Skipped
    }
  }
]
```
Any suggestion?
